language: python
python: 3.6
os: linux
dist: xenial
services:
  - docker

jobs:
  include:
    - stage: test
      install: pip install flake8==3.7.7 && pip install -r requirements.txt
      script:
        - flake8 .
    - stage: deploy
      name: 'Package code and dependency into a zip file and deploy'
      script:
        - npm install -g serverless
        - serverless plugin install -n serverless-python-requirements
        - make serverless
