language: python
python: 3.6
_aws_deplot_provider: &_aws_deploy_provider
  edge: true
  provider: lambda
  function_name: "market-watch-telegram-set-webhook"
  region: "eu-central-1"
  role: arn:aws:iam::480864162269:role/Market-Watch-Lambdas
  runtime: "python3.6"
  timeout: 30
  module_name: "market_watch.lambda_handlers"

jobs:
  include:
    - stage: test
      install: pip install flake8==3.7.7 && pip install -r requirements.txt
      script:
        - flake8 .
    - stage: deploy
      name: "Deploy crawler"
      deploy:
        <<: *_aws_deploy_provider
        handler_name: "crawl_products_handler"
    - stage: deploy
      name: "Deploy Telegram message handler"
      deploy:
        <<: *_aws_deploy_provider
        handler_name: "telegram_message_handler"
    - stage: deploy
      name: "Deploy Telegram set webhook"
      deploy:
        <<: *_aws_deploy_provider
        handler_name: "telegram_webhook_configuration_handler"
    - stage: deploy
      name: "Deploy product update handler"
      deploy:
        <<: *_aws_deploy_provider
        handler_name: "product_update_handler"
branches:
  only:
    - master
