language: python
python: 3.6
os: linux
dist: xenial
services:
  - docker

jobs:
  include:
    - stage: test
      name: lint, type check and test
      install: pip install -r requirements.txt && pip install -r requirements-test.txt
      script:
        - flake8 market_watch
        - mypy --ignore-missing-imports market_watch
        - python -m pytest market_watch
    - stage: deploy
      name: 'Package code and dependency into a zip file and deploy'
      script:
        - npm install -g serverless
        - serverless plugin install -n serverless-python-requirements
        - make serverless
